[project]
name = "grading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hypothesis>=6.131.0",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pandera>=0.23.1",
    "pytz>=2025.2",
]
